#%RAML 0.8
---
title: "User Service Subscription API"
version: v1
baseUri: http://localhost:8080/dailylog/{version}/
mediaType: application/json

schemas:
  - errorMessage: !include schemas/errorMessage-schema.json
  - subscription: !include schemas/subscription-schema.json
  - registration: !include schemas/registration-schema.json

  - registrations: |
      {  "$schema": "http://json-schema.org/draft-03/schema",
         "type": "object",
         "properties": {
           "size": {"type": "integer", "required": true},
           "registrations": {
             "type": "array",
             "items": {"$ref": "registration"}
           }
         }
      }
  - newregistration: |
      {  "$schema": "http://json-schema.org/draft-03/schema",
         "type": "object",
         "properties": {
           "userId": {"type": "string", "required": true},
           "firstname": {"type": "string", "required": true},
           "lastname": {"type": "string", "required": true},
           "email": {"type": "string", "required": true},
           "subscriptions": {"$ref": "subscription"}
          }
       }

  - partialregistration: |
      { "$schema": "http://json-schema.org/draft-03/schema",
        "type": "object",
        "properties": {
          "firstname": {"type": "string"},
          "lastname": {"type": "string"},
          "email": {"type": "string"},
          "subscriptions": {"$ref": "subscription"}
        }
      }

traits:
  - secured:
      displayName: secured
      headers:
        Authorization:
          description: The auth token for this request
      responses:
        401:
          description: Unauthorized
  - additionalHeader:
      displayName: additionalHeader
      headers:
        x-api-version:
          required: true
          description: The API implementation version
          example: 1.3.75


resourceTypes:
  - baseResource:
      is: [ additionalHeader ]
  - collection:
      type: baseResource
      get:
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName>>
                example: <<example-collection>>
          400:
            body:
              application/json:
                schema: errorMessage
      post:
        body:
          schema: <<resourcePathName | !singularize>>
          example: <<example-newmember>>
        responses:
          200:
            description: Registration has been received
          400:
            body:
              application/json:
                schema: errorMessage

  - member:
      type: baseResource
      get:
        responses:
          200:
            body:
              schema: registration
              example: <<example-member>>
      patch:
        body:
          schema: partialregistration
          example: <<example-partialmember>>
        responses:
          200:
            body:
              schema: partialregistration
              example: <<example-member>>
      delete:
        responses:
          204:

/registrations: &registrations
  type:
    collection:
      example-collection: |
        {
          "size" : 2,
          "registrations" : [
          {
            "userId" : "123",
            "firstname" : "Jane",
            "lastname" : "Doe",
            "email" : "jane.doe@test.com",
            "subscriptions" : {
              "size" : 1,
              "subscriptions" : [ {
                "serviceType" : "curr_live_rates",
                "currencyPairs" : [ "GBP", "USD" ]
              } ]
            }
          }, {
            "userId" : "345",
            "firstname" : "Max",
            "lastname" : "Mustermann",
            "email" : "max.mustermann@test.com",
            "subscriptions" : {
              "size" : 1,
              "subscriptions" : [ {
                "serviceType" : "curr_live_rates",
                "currencyPairs" : [ "GBP", "USD" ]
              } ]
            }
          } ]
        }
      example-newmember: |
        {
          "userId": "43997007",
          "firstname": "John",
          "lastname": "Smith",
          "email": "john.smith@test.hsbc.com",
          "subscriptions" : [ {
            "serviceType" : "curr_live_rates",
            "currencyPairs" : [ "GBP", "USD" ]
          } ]
        }
        example-member: |
          {
            "userId" : "123",
            "firstname" : "Jane",
            "lastname" : "Doe",
            "email" : "jane.doe@test.com",
            "subscriptions" : {
              "size" : 1,
              "subscriptions" : [ {
                "serviceType" : "curr_live_rates",
                "currencyPairs" : [ "GBP", "USD" ]
              } ]
            }
          }

  get:
    queryParameters:
      serviceType:
        description: Filter registrations by type. Either curr_live_rates or curr_historic_rates type
        required: false
